name: Create Tag

on:
  workflow_run:
    workflows: ["Test, Lint, and Build"]
    types:
      - completed
    branches:
      - main

jobs:
  push-git-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push tag
        run: ./scripts/release/create-tag.sh "${{ github.event.workflow_run.head_branch }}" 
