name: Create Tag

on:
  workflow_run:
    workflows: ["Test, Lint, and Build"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  push-git-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_commit.message, 'Merge pull request') && contains(github.event.workflow_run.head_commit.message, 'release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug workflow run info
        run: |
          echo "Triggering workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Triggering workflow name: ${{ github.event.workflow_run.name }}"
          echo "Triggering workflow head_commit: ${{ github.event.workflow_run.head_commit.message }}"
          echo "Triggering workflow head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Current workflow run ID: ${{ github.run_id }}"
          echo "Current workflow name: ${{ github.workflow }}"
          echo "Is from Test, Lint, and Build workflow: ${{ github.event.workflow_run.name == 'Test, Lint, and Build' }}"
          echo "Workflow run URL: ${{ github.event.workflow_run.html_url }}"
          echo "Workflow run status: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run artifacts URL: ${{ github.event.workflow_run.artifacts_url }}"

      - name: List available artifacts
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.workflow_run.artifacts_url }}" | jq -r '.artifacts[] | "Name: \(.name), ID: \(.id), Size: \(.size_in_bytes)"'

      - name: Download artifact directly
        run: |
          mkdir -p dist
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/brittanyrjones/hello_python/actions/artifacts/3214132805/zip" \
            -o artifact.zip
          unzip artifact.zip -d dist/
          rm artifact.zip

      - name: Create and push tag
        run: ./scripts/release/create-tag "${{ github.event.workflow_run.head_branch }}"
