name: Draft Release Branch

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      previous_version:
        description: 'Previous version (e.g., 0.3.28). If not provided, will use current version from pyproject.toml'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  draft-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure clean main branch
        run: |
          git checkout main
          git pull origin main
          git fetch --prune

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global pull.rebase false

      - name: Create release branch
        run: |
          pwd
          ls -la
          echo "Checking for pyproject.toml:"
          ls -la pyproject.toml
          echo "Checking for scripts:"
          ls -la scripts/release/
          ./scripts/release/draft-release "${{ github.event.inputs.bump_type }}" "${{ github.event.inputs.previous_version }}"
