name: Publish to Test PyPI

on:
  workflow_run:
    workflows: ["Create Tag and Release"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  check_for_moratorium:
    runs-on: ubuntu-latest
    environment: change_management
    steps:
      - uses: actions/checkout@v4
      - env:
          TPS_API_TOKEN: ${{ secrets.TPS_API_TOKEN_PARAM }}
        run: ./scripts/release/tps-check-lock hello_python ${{ github.sha }}

  publish:
    needs: check_for_moratorium
    runs-on: ubuntu-latest
    environment: change_management
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts-${{ github.event.inputs.build_ref || github.ref_name }}
          path: dist/
          merge-multiple: true

      - name: Release to Test PyPI
        if: ${{ github.event.inputs.target == 'testpypi' }}
        run: uv publish --repository https://test.pypi.org/legacy/ dist/*

      - name: Publish To Change Management
        env:
          ACTOR_EMAIL: ${{ secrets.TPS_API_RELEASE_ACTOR_EMAIL }}
          TPS_API_TOKEN: ${{ secrets.TPS_API_TOKEN_PARAM }}
        run: ./scripts/release/tps-record-release hello_python ${{ github.sha }}
