name: Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Debug tag info
        run: |
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub ref name: ${{ github.ref_name }}"
          echo "GitHub ref type: ${{ github.ref_type }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event before: ${{ github.event.before }}"
          echo "Event after: ${{ github.event.after }}"

      - uses: actions/checkout@v4

      - name: Get build workflow run
        id: build_run
        run: |
          # Get the commit that this tag points to
          COMMIT_SHA=$(git rev-parse ${{ github.ref }})
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          
          # Get the workflow run that created this commit
          RUN_ID=$(gh api repos/${{ github.repository }}/commits/$COMMIT_SHA/check-runs | jq -r '.check_runs[] | select(.name=="Test, Lint, and Build") | .id')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Found build workflow run: $RUN_ID"

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts-main
          path: dist/
          run-id: ${{ steps.build_run.outputs.run_id }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true 