name: Test, Lint, and Build

permissions:
  contents: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-lint-build:
    name: Test, Lint, and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        id: setup-python

      - name: Get Python version from pyproject.toml
        id: pyproject-version
        run: |
          VERSION=$(grep "requires-python" pyproject.toml | sed 's/requires-python = ">=\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Matrix Python version: ${{ matrix.python-version }}"
          echo "PyProject Python version: $VERSION"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Is matching version: ${{ matrix.python-version == steps.pyproject-version.outputs.version }}"
          echo "Is push to main: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
          echo "Contains release-v: ${{ contains(github.event.head_commit.message, 'release-v') }}"
          echo "Full condition: ${{ matrix.python-version == steps.pyproject-version.outputs.version && github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release-v') }}"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-glob: pyproject.toml

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Install ruff
        run: uv pip install ruff
        
      - name: Run linting
        run: uv run ruff check .

      - name: Run tests
        run: uv run tox

      - name: Build artifact
        run: uv build

      - name: Debug upload conditions
        run: |
          echo "Matrix Python version: ${{ matrix.python-version }}"
          echo "PyProject Python version: ${{ steps.pyproject-version.outputs.version }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Is matching version: ${{ matrix.python-version == steps.pyproject-version.outputs.version }}"
          echo "Is push to main: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
          echo "Contains release-v: ${{ contains(github.event.head_commit.message, 'release-v') }}"
          echo "Full condition: ${{ matrix.python-version == steps.pyproject-version.outputs.version && github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release-v') }}"
          echo "Current directory contents:"
          ls -la dist/

      - name: Upload artifacts
        if: ${{ matrix.python-version == steps.pyproject-version.outputs.version && github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'release-v') }}
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-main
          path: dist/
          retention-days: 90
